---
- name: Communicating with InfoBlox API
  connection: local
  hosts: localhost
  gather_facts: no

  ## python3 -m pip install infoblox-client

  vars:
          state: present
          nios_provider:
                  host: 192.168.70.65
                  username: admin
                  password: cowcow!

  tasks:
          - name: Create a forward DNS Zone
            nios_zone:
                    name: rzfeeser.com
                    comment: a local DNS zone
                    state: "{{ state }}"
                    provider: "{{ nios_provider }}"

          - name: Create a network on the default network view
            nios_network:
                    network: 192.168.100.0/24
                    comment: Attempting to set an IPv4 network
                    options:
                            - name: domain-name
                              value: rzfeeser.com
                    state: "{{ state }}"
                    provider: "{{ nios_provider }}"
            register: results

          - name: display the results
            debug:
                    var: results

          - name: configure an IPv4 host record
            nios_host_record:
                    name: polarpickle.rzfeeser.com
                    ipv4addrs:
                            - ipv4addr:
                                    "{{ lookup('nios_next_ip', '192.168.100.0/24', provider=nios_provider )[0] }}"
                    state: "{{ state }}"
                    provider: "{{ nios_provider }}"
            register: results

          - name: display the results
            debug:
                    var: results
