---
- name: Harvest running config from Palo Alto PanOS
  hosts: localhost
  connection: local
  gather_facts: no

  ## file to store credentials mapped to provider
  vars_files:
          - ~/panoscreds.yml

  ## call to the collection
  collections:
        - paloaltonetworks.panos

  tasks:

        - name: Grab some facts about a PanOS device
          panos_facts:
              provider: '{{ provider }}'
              gather_subset: ['config']
          register: resultz

        - name: what was returned to panos_facts?
          debug:
              var: resultz

