---
- name: Extra vars vault
  hosts: localhost

  # reference the encrypted variable file
  vars_files:
    - vars/oscreds.yml

  tasks:
    - name: print out encrypted vars
      debug:
        msg: "{{ imscloud }}"
      no_log: true   # supress output (no logging will be done on this task)
